# Generated by Django 4.2.5 on 2023-10-25 10:43

from django.db import migrations


def populate_locale(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Locales = apps.get_model("users", "SupportedLocales")
    Locales.objects.create(code="en-US", name="English")
    Locales.objects.create(code="pt-BR", name="Portuguese")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_locale),
    ]
