# Generated by Django 4.2.5 on 2023-10-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="nickname",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="locale",
            field=models.CharField(
                choices=[("en-us", "English"), ("pt-br", "Portuguese")],
                default="en-us",
                max_length=5,
            ),
        ),
    ]
