# Generated by Django 4.2.5 on 2024-03-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_populate_locales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="locale",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.supportedlocales",
            ),
        ),
    ]
