# Generated by Django 4.1.2 on 2023-10-30 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_community_consumergroup_producergroup_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumergroup",
            name="communities",
        ),
        migrations.RemoveField(
            model_name="producergroup",
            name="communities",
        ),
        migrations.AddField(
            model_name="community",
            name="consumer_groups",
            field=models.ManyToManyField(to="users.consumergroup"),
        ),
        migrations.AddField(
            model_name="community",
            name="producer_groups",
            field=models.ManyToManyField(to="users.producergroup"),
        ),
        migrations.AddField(
            model_name="consumergroup",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="producergroup",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
