# Generated by Django 4.2.5 on 2023-10-31 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_consumergroup_communities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consumergroup",
            name="users",
        ),
        migrations.RemoveField(
            model_name="consumergroupcommunityinvitation",
            name="community",
        ),
        migrations.RemoveField(
            model_name="consumergroupcommunityinvitation",
            name="consumer",
        ),
        migrations.RemoveField(
            model_name="producergroup",
            name="users",
        ),
        migrations.RemoveField(
            model_name="producergroupcommunityinvitation",
            name="community",
        ),
        migrations.RemoveField(
            model_name="producergroupcommunityinvitation",
            name="producer",
        ),
        migrations.RemoveField(
            model_name="userconsumerinvitations",
            name="group",
        ),
        migrations.RemoveField(
            model_name="userconsumerinvitations",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userproducerinvitations",
            name="group",
        ),
        migrations.RemoveField(
            model_name="userproducerinvitations",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="groups",
        ),
        migrations.DeleteModel(
            name="Community",
        ),
        migrations.DeleteModel(
            name="ConsumerGroup",
        ),
        migrations.DeleteModel(
            name="ConsumerGroupCommunityInvitation",
        ),
        migrations.DeleteModel(
            name="ProducerGroup",
        ),
        migrations.DeleteModel(
            name="ProducerGroupCommunityInvitation",
        ),
        migrations.DeleteModel(
            name="UserConsumerInvitations",
        ),
        migrations.DeleteModel(
            name="UserProducerInvitations",
        ),
    ]
