# Generated by Django 4.2.5 on 2024-03-21 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GenericSocialLink",
            new_name="SocialLink",
        ),
        migrations.AlterUniqueTogether(
            name="sociallink",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="consumergroup",
            name="user_creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_consumer_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sociallink",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="groups_soci_content_33735a_idx",
            ),
        ),
    ]
